In [78]:
import numpy as np
import pandas as pd

In [79]:
pd.read_csv('P:/PROGRAMMING/PYTHON/TUTEDUE/GEN AI/PRACTICE/DATASET FROM KAGGLE/YouTube Trending Videos Stats 2026/BR_Trending.csv')

               channel_title    views  Unnamed: 2
0          MC Negão Original   165496         NaN
1               ingresso.com    90535         NaN
2                Brawl Stars  2058940         NaN
3                      NMIXX   164264         NaN
4           ONE Media Brasil    86016         NaN
...                      ...      ...         ...
16195  Dilson Castro - Topic      110         NaN
16196  Dilson Castro - Topic      127         NaN
16197  Dilson Castro - Topic      373         NaN
16198  Dilson Castro - Topic      258         NaN
16199  Dilson Castro - Topic       48         NaN

[16200 rows x 3 columns]

In [80]:
pd.read_csv('data.csv').squeeze('columns')

FileNotFoundError: [Errno 2] No such file or directory: 'data.csv'

In [ ]:
pd.read_csv('data.csv').squeeze('columns')

In [ ]:
pd.read_csv('dataa_2_col.csv',index_col='Channel name').squeeze('columns')

In [ ]:
# Exact match use karein
result = pd.read_csv('dataa_2_col.csv', index_col='Channel Name').squeeze('columns')

ValueError: Index Channel Name invalid

In [ ]:
dataframe = pd.read_csv('dataa_2_col.csv',index_col = 'views').squeeze('columns')

In [ ]:
df = pd.read_csv('data_1_col.csv').squeeze('columns')

In [ ]:
pd.read_csv('dataa_2_col.csv').squeeze('columns')

In [ ]:
df.values

In [ ]:
dataframe.values

In [ ]:
dataframe.astype('int32')

In [ ]:
dataframe.shape

In [ ]:
dataframe.ndim

In [ ]:
df.name

In [ ]:
df.is_unique

In [ ]:
df.head(11)

In [ ]:
df.tail()

In [ ]:
df.sample()

In [ ]:
df.value_counts

In [ ]:
youtube = pd.read_csv('new.csv')

In [ ]:
youtube

In [ ]:
avg = youtube['likes (min)']

In [ ]:
youtube.sort_values()

In [ ]:
df.sort_values(ascending=False)

In [82]:
df.sort_index()

      trending_date  Unnamed: 1  Unnamed: 2
0          26.26.02         NaN         NaN
1          26.26.02         NaN         NaN
2          26.26.02         NaN         NaN
3          26.26.02         NaN         NaN
4          26.26.02         NaN         NaN
...             ...         ...         ...
16195      26.26.02         NaN         NaN
16196      26.26.02         NaN         NaN
16197      26.26.02         NaN         NaN
16198      26.26.02         NaN         NaN
16199      26.26.02         NaN         NaN

[16200 rows x 3 columns]